import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { Report, ReportType } from '@/lib/db';

const typeLabels: Record<ReportType, string> = {
  general: 'General Clinical Note',
  soap: 'SOAP Notes',
  diagnostic: 'Surgical Pathology Report',
};

export function exportReportToPDF(report: Report, hospitalName = 'Medical Center', address = 'Address') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = 20;

  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(hospitalName, pageWidth / 2, yPos, { align: 'center' });
  yPos += 6;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(address, pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  // Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(typeLabels[report.reportType], pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  // Horizontal line
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  // Metadata section
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const metadata = [
    ['Date:', format(new Date(report.createdAt), 'MMMM d, yyyy h:mm a')],
    ['Report Type:', typeLabels[report.reportType]],
    ['Duration:', `${Math.floor(report.duration / 60)}:${(report.duration % 60).toString().padStart(2, '0')}`],
    ['Word Count:', String(report.wordCount)],
  ];

  metadata.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 30, yPos);
    yPos += 6;
  });

  yPos += 5;
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Report content
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(report.reportContent, contentWidth);
  
  lines.forEach((line: string) => {
    if (yPos > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      yPos = 20;
    }
    
    // Check if line is a section header (all caps or ends with colon)
    const isHeader = line === line.toUpperCase() && line.length > 3 || 
                     /^[A-Z][A-Za-z\s]+:$/.test(line.trim());
    
    if (isHeader) {
      doc.setFont('helvetica', 'bold');
      yPos += 3;
    } else {
      doc.setFont('helvetica', 'normal');
    }
    
    doc.text(line, margin, yPos);
    yPos += 6;
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      `Generated by MediVoice • ${format(new Date(), 'MM/dd/yyyy')}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 15,
      { align: 'center' }
    );
  }

  return doc;
}

export function downloadReportAsPDF(report: Report) {
  const doc = exportReportToPDF(report);
  const fileName = `medivoice-report-${format(new Date(report.createdAt), 'yyyy-MM-dd-HHmm')}.pdf`;
  doc.save(fileName);
}
